// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	client "github.com/ava-labs/avalanche-network-runner/client"
	mock "github.com/stretchr/testify/mock"
)

// getGRPCClientFunc is an autogenerated mock type for the getGRPCClientFunc type
type getGRPCClientFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *getGRPCClientFunc) Execute() (client.Client, error) {
	ret := _m.Called()

	var r0 client.Client
	if rf, ok := ret.Get(0).(func() client.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewGetGRPCClientFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newGetGRPCClientFunc creates a new instance of getGRPCClientFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newGetGRPCClientFunc(t mockConstructorTestingTnewGetGRPCClientFunc) *getGRPCClientFunc {
	mock := &getGRPCClientFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
