// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PluginBinaryDownloader is an autogenerated mock type for the PluginBinaryDownloader type
type PluginBinaryDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: vmIDs, pluginDir, binDir
func (_m *PluginBinaryDownloader) Download(vmIDs map[string]struct{}, pluginDir string, binDir string) error {
	ret := _m.Called(vmIDs, pluginDir, binDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]struct{}, string, string) error); ok {
		r0 = rf(vmIDs, pluginDir, binDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadVM provides a mock function with given fields: vmID, pluginDir, binDir
func (_m *PluginBinaryDownloader) DownloadVM(vmID string, pluginDir string, binDir string) error {
	ret := _m.Called(vmID, pluginDir, binDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(vmID, pluginDir, binDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPluginBinaryDownloader interface {
	mock.TestingT
	Cleanup(func())
}

// NewPluginBinaryDownloader creates a new instance of PluginBinaryDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPluginBinaryDownloader(t mockConstructorTestingTNewPluginBinaryDownloader) *PluginBinaryDownloader {
	mock := &PluginBinaryDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
