// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PromptRunner is an autogenerated mock type for the PromptRunner type
type PromptRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *PromptRunner) Run() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetValidation provides a mock function with given fields: _a0
func (_m *PromptRunner) SetValidation(_a0 func(string) error) {
	_m.Called(_a0)
}
