// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// setDefaultSnapshotFunc is an autogenerated mock type for the setDefaultSnapshotFunc type
type setDefaultSnapshotFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *setDefaultSnapshotFunc) Execute(_a0 string, _a1 bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewSetDefaultSnapshotFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newSetDefaultSnapshotFunc creates a new instance of setDefaultSnapshotFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newSetDefaultSnapshotFunc(t mockConstructorTestingTnewSetDefaultSnapshotFunc) *setDefaultSnapshotFunc {
	mock := &setDefaultSnapshotFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
