name: avalanche-cli
services:
  icm-relayer:
    image: avaplatform/icm-relayer:{{ .ICMRelayerVersion }}
    container_name: icm-relayer
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    network_mode: "host"
    volumes:
      - /home/ubuntu/.avalanche-cli/services/icm-relayer:/.icm-relayer:rw
    command: 'icm-relayer --config-file /.icm-relayer/icm-relayer-config.json'
