# https://golangci-lint.run/usage/configuration/
linters-settings:
  depguard:
    list-type: denylist
    packages:
      - io/ioutil
    packages-with-error-message:
      - io/ioutil: 'use package io or os instead'