apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: avalanche-cli
  description: |
    Avalanche-CLI is a command-line interface for building, deploying, and maintaining Avalanche
    Subnets. It can be used to support the entire Subnet development lifecycle from initial
    prototyping to production deployments. Avalanche-CLI is available for Linux and Mac, and is open
    source on GitHub.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ava-labs/avalanche-cli
spec:
  type: service
  owner: platform-tooling
  lifecycle: production
  system: platform
  dependsOn:
    - component:avalanchego
    - component:avalanche-network-runner
    - resource:posthog
    - component:subnet-evm
    - component:coreth
    - component:apm
