server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://{{ .IP }}:{{ .Port}}/loki/api/v1/push


scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - static_labels:
          job: docker
    relabel_configs:
      - source_labels:
          - '__meta_docker_container_name'
        regex: '/(.*)'
        target_label: 'container'
      - source_labels:
          - '__meta_docker_container_label_com_docker_compose_project'
        regex: '(.*)'
        target_label: 'compose_project'
      - source_labels:
          - '__meta_docker_container_label_com_docker_compose_container_number'
        regex: '(.*)'
        target_label: 'compose_container_number'
      - source_labels:
          - '__meta_docker_container_label_com_docker_compose_project_config_files'
        regex: '(.*)'
        target_label: 'compose_project_config_files'
      - source_labels:
          - '__meta_docker_container_label_com_docker_compose_service'
        regex: '(.*)'
        target_label: 'compose_service'
  - job_name: avalanchego
    pipeline_stages:
      - regex:
          expression: '\[(?P<timestamp>\d{2}-\d{2}\|\d{2}:\d{2}:\d{2}\.\d{3})\]'
      - timestamp:
          source: timestamp
          format: '03-20|01:34:31.515'
    static_configs:
    - targets:
        - localhost
      labels:
        job: c-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/C.log
    - targets:
        - localhost
      labels:
        job: p-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/P.log
    - targets:
        - localhost
      labels:
        job: x-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/X.log
    - targets:
        - localhost
      labels:
        job: main
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/main.log
{{ if .ChainID }}
    - targets:
        - localhost
      labels:
        job: subnet
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: {{ .ChainID }}
{{ end }}
  - job_name: avalanchego-loadtest
    static_configs:
    - targets:
        - localhost
      labels:
        job: loadtest
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /home/ubuntu/loadtest_*.txt
