{
 "title": "Loadtest Simulator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Error Distribution by Cause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_errors_total[$__rate_interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "tx_confirmation_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tx_confirmation_time", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "tx_issuance_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tx_issuance_time", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "tx_issuance_to_confirmation_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tx_issuance_to_confirmation_time",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}