// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ids "github.com/ava-labs/avalanchego/ids"
	mock "github.com/stretchr/testify/mock"
)

// BinaryDownloader is an autogenerated mock type for the BinaryDownloader type
type BinaryDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: _a0, _a1
func (_m *BinaryDownloader) Download(_a0 ids.ID, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(ids.ID, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
