// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ids "github.com/ava-labs/avalanchego/ids"
	mock "github.com/stretchr/testify/mock"
)

// PluginBinaryDownloader is an autogenerated mock type for the PluginBinaryDownloader type
type PluginBinaryDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: vmID, pluginDir, binDir
func (_m *PluginBinaryDownloader) Download(vmID ids.ID, pluginDir string, binDir string) error {
	ret := _m.Called(vmID, pluginDir, binDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(ids.ID, string, string) error); ok {
		r0 = rf(vmID, pluginDir, binDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
