// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	common "github.com/ava-labs/avalanchego/snow/engine/common"

	mock "github.com/stretchr/testify/mock"
)

// Indexer is an autogenerated mock type for the Indexer type
type Indexer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Indexer) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterChain provides a mock function with given fields: name, engine
func (_m *Indexer) RegisterChain(name string, engine common.Engine) {
	_m.Called(name, engine)
}
