name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-24.04
    steps:
      - name: PR Auto Assignee
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/config/auto_assign.yml"
